#! /usr/bin/env python

import genomon_pipeline
import argparse

parser = argparse.ArgumentParser(prog = "genomon_runner")

parser.add_argument("--version", action = "version", version = "genomon_pipeline-" + genomon_pipeline.__version__)

parser.add_argument('script', metavar = "/path/to/singularity_bwa.sh", type = str, help = "input singularity script")
parser.add_argument("conf", metavar = "/path/to/sample.conf.yml", type = str, help = "input sample list flie [YAML]")
parser.add_argument("--drmaa", help = "with drmaa", action='store_true')
parser.set_defaults(handler=genomon_pipeline.run_engine.main)

args = parser.parse_args()

args.handler(args)
